make functional data compliant with latest build runner and flutter 2.2
spkersten/dart_functional_data pull request #27
Opened 2021-05-22 08:31 UTC by remonh87

We would like to upgrade some outdated dependencies on reactive ble but we cannot do this since functional data still relies on an older version of build_runner. This pr fixes it

2021-05-22 08:32 UTC, remonh87 commented on example/bin/main.g.dart
> -// ignore_for_file: join_return_with_assignment
these lint rules are deprecated and thus not needed anymore :)

2021-05-26 12:18 UTC, spkersten requested changes

2021-05-26 12:18 UTC, spkersten commented on functional_data_generator/lib/builder.dart
> +    SharedPartBuilder([FunctionalDataGenerator()], 'functional_data');
Looks like you accidentally reformatted the file with a max line length smaller than 120

2021-05-29 13:03 UTC, spkersten commented
I've merged the changes. I don't think the ignored lint rules are deprecated. There were warnings about duplicate "ignore_for_file" comments though. I've changed the code a bit so some of those warnings won't occur anymore and made the "ignore" comments for the remaining ones local.

Published as: https://pub.dev/packages/functional_data_generator/versions/1.0.1

2021-05-29 13:03 UTC, closed without merging